title: "Idea / RFC"
labels: ["enhancement", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Use this to propose new features or API changes before opening a PR.
        The more concrete the use-case, the better.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Problem
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: Describe the proposed behavior and how users would use it.
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API / Design Sketch (optional)
      description: If you have a rough idea of the public API, put it here.
      render: java
    validations:
      required: false

  - type: textarea
    id: breaking
    attributes:
      label: Breaking Changes / Migration
      description: Would this be breaking? If yes, what would migration look like?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (estimate)
      options:
        - low
        - medium
        - high
    validations:
      required: true
