title: "Q&A / Help"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Use this for usage questions and help requests.
        For reproducible bugs, please open an Issue instead.

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: e.g. 0.5.0 (or main @ <commit>)
    validations:
      required: false

  - type: dropdown
    id: module
    attributes:
      label: Module
      options:
        - api
        - core
        - codec
        - testkit
        - cli
        - schema-tools
        - spring-boot-starter
        - other / unknown
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What are you trying to accomplish?
      placeholder: Be specific about the desired outcome.
    validations:
      required: true

  - type: textarea
    id: what_tried
    attributes:
      label: What did you try?
      description: Include minimal code/config and what happened.
      render: java
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Anything else that helps (stacktraces, links, constraints).
    validations:
      required: false
